spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: 2.0

cards:
  message: "Welcome to Production CARDS-service2222 github  APIs"
  contact-details:
    name: "Omar card-service-------------------"
    email: "omar@example.com"

  on-call-support:
    - "01000000000"
    - "01111111111"
