spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: 2.0

cards:
  message: "Welcome to Production CARDS-service2222 github  APIs"
  contact-details:
    name: "Omar card-servicedynamic dynamic dynamic dynamicesdgasag test dynamic"
    email: "{cipher}e60a5677dde03d20fd3afa614f3b7232c73555cc2f14221a13d5c71ab92d83e8061b5cef9bc7b74dc0aa5d815820f6eb"

  on-call-support:
    - "01000000000"
    - "01111111111"
