spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: 2.0

cards:
  message: "Welcome to qa loans-service  APIs"
  contact-details:
    name: "Omar card-service"
    email: "omar@example.com test refresh"

  on-call-support:
    - "01000000000"
    - "01111111111"
