spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: 2.0

loans:
  message: "Welcome to Production loans-service  APIs"
  contact-details:
    name: "Omar production-----------------------"
    email: "omar@example.com"

  on-call-support:
    - "01000000000"
    - "01111111111"
